pipeline
    agent any

    environment {
        AZURE_CLIENT_ID = credentials('azure_client_id')
        AZURE_CLIENT_SECRET = credentials('azure_client_secret')
        AZURE_TENANT_ID = credentials('azure_tenant_id')
    }

    parameters {
        string(name: 'account_name', description: 'Storage Account Name')
        string(name: 'container_name', description: 'Container Name')
        string(name: 'blob_name', description: 'Blob Name')
        string(name: 'file_name', description: 'File Name')
    }

    stages {
        stage('Login') {
            steps {
                az login --service-principle -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            }
        }
        stage('Download a file from the Storage Account') {
            steps {
                az storage blob download --account-name "${params.account_name}" --container-name "${params.container_name}" --name "${params.blob_name}" --file "${params.file_name}" --auth-mode login
            }
        }
        stage('Change the file content') {
            steps {
                sh 'change some string in the text and save it back, under the same name'
            }
        }
        stage('Upload file to the Storage Account') {
            steps {
                az storage blob upload --account-name "${params.account_name}" --container-name "${params.container_name}" --name "${params.blob_name}" --file "${params.file_name}" --auth-mode login --overwrite true
            }
        }
    }